name: Manual Tailscale Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag, branch, or commit hash of the action to use"
        default: "main"

jobs:
  test-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Tailscale
        uses: tailscale/github-action@{{ github.event.inputs.ref }}
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: github-actions-monitoring
          ephemeral: true

      - name: Show current Tailscale status
        run: tailscale status
