name: Manual Tailscale Test

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: github-actions-monitoring
          ephemeral: true

      - name: Show current Tailscale status
        run: tailscale status
