name: Manual Tailscale Test

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Tailscale
        uses: tailscale/github-action@max/add-retry
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Show current Tailscale status
        run: tailscale status
