name: Manual Tailscale Test

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Tailscale
        uses: tailscale/github-action@029c99af76d53fa362a1168429bcb3aff9793c45
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          retry: 3

      - name: Show current Tailscale status
        run: tailscale status
