name: Manual Tailscale Test

on:
  workflow_dispatch:

jobs:
  test-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Tailscale
        uses: tailscale/github-action@7e6046c1f4838fcabc959d130a72d70faec525a0
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Show current Tailscale status
        run: tailscale status
