name: Manual Tailscale Test

on:
  workflow_dispatch:

jobs:
  test-tailscale-github-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'v3'
          - 'main'

    steps:
      - name: test tailscale github action version ${{ matrix.version }}
        uses: tailscale/github-action@${{ matrix.version }}
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: github-actions-monitoring

      - name: Show current Tailscale status
        run: tailscale status
